name: Android Emulator WDIO Tests

on:
  workflow_dispatch:

jobs:
  wdio-android:
    runs-on: macos-latest
    timeout-minutes: 40

    steps:
      # 1Ô∏è‚É£ Checkout repository
      - uses: actions/checkout@v4

      # 2Ô∏è‚É£ Set up Android Emulator
      
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.35.0
        with:
          api-level: 33
          # target: google_apis
          # arch: arm64-v8a
          # emulator-options: -no-window -no-audio -gpu swiftshader_indirect -accel off

      # üîü Start Appium server
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --log-level error --allow-insecure=chromedriver_autodownload &
          sleep 10

      # 1Ô∏è‚É£1Ô∏è‚É£ Run WDIO tests
      - name: Run WDIO Tests
        run: npx wdio run wdio.conf.ts
