name: Android Emulator WDIO

on:
  workflow_dispatch:

env:
  API_LEVEL: 33
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  EMULATOR_NAME: android-emulator

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Add Android tools to PATH
        run: |
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install emulator & system image
        run: |
          sdkmanager "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
          sdkmanager "platform-tools" "emulator"

      - name: Set AVD env
        run: |
          echo "ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV
          mkdir -p $HOME/.android/avd

      - name: Install emulator image
        run: |
          sdkmanager "platform-tools" "emulator" \
            "system-images;android-33;google_apis;x86_64"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd \
            --name android-emulator \
            --package "system-images;android-33;google_apis;x86_64" \
            --device pixel

      - name: Verify AVD
        run: emulator -list-avds

      - name: Start emulator
        run: |
          emulator -avd android-emulator \
            -no-window -no-audio -gpu swiftshader_indirect &


      - name: Wait for emulator
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed | grep 1
          adb devices

      - name: Start Appium
        run: |
          npm install -g appium
          appium --log-level error &
          sleep 10

      - name: Run WDIO tests
        run: npx wdio run wdio.conf.ts
